[theme]
base = "dark"
primaryColor = "#007bff"

[server]
headless = true
enableXsrfProtection = false
enableCORS = false

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true

[logger]
level = "error"

[ui]
hideTopBar = false
hideSidebarNav = true
hideSidebar = true

[theme.base]
base="dark"

[layout]
contentWidth = 1200

[runner]
fastReruns = true
