[theme]
base = "dark"
primaryColor = "#007bff"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FFFFFF"

[server]
enableCORS = false
enableXsrfProtection = false
headless = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true

[logger]
level = "error"

[runner]
fastReruns = true
